# Uncomment the next line to define a global platform for your project
 platform :ios, '8.0'

target 'wangyiNews' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for wangyiNews

pod 'AFNetworking','~>3.1.0'
pod 'YYModel','~>1.0.4'
pod 'SDWebImage','~>4.0.0-beta2'
pod 'Masonry','~>1.0.2'
end
